name: Qexo_Json_to_circle

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5  * * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.8
        
    - name: Import requests
      run: |
          pip install requests

    - name: Qexo_Json_to_circle
      working-directory: ./Qexo_Json_to_circle
      run: |
        python Qexo_Json.py
        
        
    - name: commit
      run: |
        git config --global user.email 2015078351@qq.com
        git config --global user.name Bytelv
        git add friends.json
        git commit -m "update" -a
      
        
    - name: Push changes
      uses: Bytelv/Scrpits-librart@output
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

