name: Qexo_Json_to_circle

on:
  push:
    branches:
      - main
 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.8
        
    - name: Import requests
      run: |
          pip install requests

    - name: Qexo_Json_to_circle
      working-directory: ./Qexo_Json_to_circle
      run: |
        python Qexo_Json.py
        
    - name: ls
      working-directory: ./Qexo_Json_to_circle
      run: |
        ls
        
    - name: Read_json
      working-directory: ./Qexo_Json_to_circle
      run: |
        cat friends.json | jq
    
        
    
    - name: Push
      run: |
        git config --global --unset http.proxy
        git config --global --unset https.proxy
        git config --local user.email "2015078351@qq.com"
        git config --local user.name "Bytelv"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
        git add ./Qexo_Json_to_circle/friends.json
        git commit -m "push friends.json"
        git push

    
        

