name: Qexo_Json_to_circle

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5  * * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.8
        
    - name: Import requests
      run: |
          pip install requests

    - name: Qexo_Json_to_circle
      working-directory: ./Qexo_Json_to_circle
      run: |
        python Qexo_Json.py
        
    - name: ls
      working-directory: ./Qexo_Json_to_circle
      run: |
        ls
        
    - name: Read_json
      working-directory: ./Qexo_Json_to_circle
      run: |
        cat friends.json | jq
    
        
    
        
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.TOKEN }}
        repository: Bytelv/Scripts-library
        push-branch: 'main'
        commit-message: 'publish'
        force-add: 'true'
        files: ./Qexo_Json_to_circle/friends.json
        name: Bytelv
        email: 2015078351@qq.com

    
        

